///////////////////////////////////////////////////////////
//  Controller.cs
//  Implementation of the Class Controller
//  Generated by Enterprise Architect
//  Created on:      22-2ÔÂ-2017 22:34:19
//  Original author: Doku
///////////////////////////////////////////////////////////

namespace ECharts.Entities
{
    public class Controller
    {
        public VisualItem inRange { get; set; }

        public VisualItem outOfRange { get; set; }

        public VisualItem InRange()
        {
            if (inRange == null)
                inRange = new VisualItem();
            return inRange;
        }


        public VisualItem OutOfRange()
        {
            if (outOfRange == null)
                outOfRange = new VisualItem();
            return outOfRange;
        }

        /// <param name="inRange"></param>
        public Controller InRange(VisualItem inRange)
        {
            this.inRange = inRange;
            return this;
        }

        /// <param name="outOfRange"></param>
        public Controller OutOfRange(VisualItem outOfRange)
        {
            this.outOfRange = outOfRange;
            return this;
        }
    } //end Controller
} //end namespace Entities